server:
  port: 9008
spring:
  application:
    name: dym-sms
  rabbitmq:
    host: 192.168.244.131`
    port: 5672
    username: keqing
    password: lang520
sms:
  appcode: 6c19c4c303614448a1712e6446ded091 #使用自己的AppCode
  tpl_id: TP1711063    # 默认模板