spring:
  servlet:
    multipart:
      max-file-size: 1050MB
      max-request-size: 1060MB
  application:
    name: dym-file
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true

FILE_SERVER_URL: http://192.168.244.131:8080/