server:
  port: 9100
spring:
  application:
    name: user-oauth
  datasource:
    url: jdbc:mysql://192.168.244.131:33306/dongyimaidb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
encrypt:
  key-store:
    location: classpath:dongyimai.jks  #秘钥文件名
    alias: dongyimai  #别名
    password: dongyimai  #密码
    secret: dongyimai   #密钥库的访问密码
auth:
  ttl: 3600  #token过期时间
  clientId: admin  #客户端id
  clientSecret: admin #客户端密码
  cookieDomain: localhost #cookie域名
  cookieMaxAge: -1     #cookie有效期


# 开启Feign的熔断功能
feign:
  hystrix:
    enabled: true
#总连接超时时间=（切换服务实例次数+1）*（每个实例重试次数+1）*连接超时时间
DYM-USER: #服务名称
  ribbon:
    #配置指定服务的负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # Ribbon的连接超时时间
    ConnectTimeout: 2000
    # Ribbon的数据读取超时时间
    ReadTimeout: 2000
    # 是否对所有操作都进行重试
    OkToRetryOnAllOperations: true
    # 切换实例的重试次数
    MaxAutoRetriesNextServer: 1
    # 对当前实例的重试次数
    MaxAutoRetries: 1
#设定Hystrix熔断超时时间 ，理论上熔断时间应该大于总连接超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000