server:
  port: 9004
spring:
  redis:
    host: 192.168.244.131
    port: 6379
  application:
    name: dym-search
  elasticsearch:
    rest:
      uris: 192.168.244.131:9200  #此处配置elasticsearch的访问地址
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
#超时配置
ribbon:
  ReadTimeout: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000